"use client";
import { useCallback, useEffect, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import type { ActivityLog } from "@/lib/types";
import { DateFilterBar } from "@/components/ui/DateFilterBar";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { useToast } from "@/contexts/ToastContext";
import { createDefaultDateFilter, toApiQueryParams, type DateFilterState } from "@/lib/utils/dateFilter";
import { formatDateTimeShort } from "@/lib/utils/formatters";
export default function KurirLogPage(): JSX.Element { const { showToast } = useToast(); const [filter, setFilter] = useState<DateFilterState>(createDefaultDateFilter()); const [items, setItems] = useState<ActivityLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.cod.kurirLog(toApiQueryParams(filter))).data ?? []); } catch (e) { const message = e instanceof ApiError ? e.message : "Gagal memuat log kurir"; setError(message); showToast(message, "error"); } finally { setLoading(false); } }, [filter, showToast]); useEffect(() => { void load(); }, [load]); return <div className="space-y-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-semibold tracking-[-0.03em] text-jp-text dark:text-jp-text-dark">Log Aktivitas Kurir</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Riwayat penerimaan dan pembaruan status COD</p></div><DateFilterBar currentFilterState={filter} onFilterStateChange={setFilter}/></div>{loading ? <LoadingSkeleton numberOfRows={6}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="overflow-hidden rounded-2xl border border-jp-border bg-jp-surface dark:border-jp-border-dark dark:bg-jp-surface-dark">{items.length ? items.map((item) => <div key={item.id} className="flex items-start gap-4 border-b border-jp-border dark:border-jp-border-dark px-6 py-4 last:border-0"><div className="mt-2 h-1.5 w-1.5 rounded-full bg-zinc-400"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-medium">{item.user}</span><span className="badge">{item.action||item.aksi||"-"}</span></div><p className="mt-1 text-[11px] text-jp-muted dark:text-jp-muted-dark">{item.target || item.detail || "-"}{item.cabang ? ` · ${item.cabang}` : ""}</p></div><span className="whitespace-nowrap text-[10px] text-jp-muted dark:text-jp-muted-dark">{formatDateTimeShort(item.timestamp||item.waktu)||"-"}</span></div>) : <EmptyState message="Belum ada log aktivitas" iconName="clockSvg"/>}</div>}</div>; }
