"use client";

import { useCallback, useEffect, useState } from "react";
import { Api, ApiError, type ServiceUpdatePayload } from "@/lib/api";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { ImageUploader } from "@/components/ui/ImageUploader";
import { LabelledInput, LabelledSelect, LabelledTextarea } from "@/components/ui/InputField";
import { formatDateTimeShort } from "@/lib/utils/formatters";
import { ServiceStatusBadge } from "@/components/ui/Badge";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import type { ServiceStatus, ServiceTicket, UploadedImage } from "@/lib/types";

export default function ServiceListPage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast(); const [items, setItems] = useState<ServiceTicket[]>([]); const [filter, setFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<ServiceTicket | null>(null); const [status, setStatus] = useState<ServiceStatus>("Antrian"); const [note, setNote] = useState(""); const [technician, setTechnician] = useState(""); const [estimate, setEstimate] = useState(""); const [before, setBefore] = useState<UploadedImage[]>([]); const [after, setAfter] = useState<UploadedImage[]>([]); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.service.list({ limit: 50 })).data ?? []); } catch (e) { setError(e instanceof ApiError ? e.message : "Gagal memuat service"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const openEdit = async (id: string) => { try { const service = (await Api.service.get(id)).data; setEditing(service); setStatus(service.status); setNote(service.catatan_kerusakan || ""); setTechnician(service.teknisi || user?.name || ""); setEstimate(service.estimasi_selesai ? service.estimasi_selesai.replace(" ", "T").slice(0,16) : ""); setBefore((service.foto_before_urls || []).map((secure_url) => ({ secure_url }))); setAfter((service.foto_after_urls || []).map((secure_url) => ({ secure_url }))); } catch (e) { showToast(e instanceof Error ? e.message : "Detail service gagal", "error"); } };
  const save = async () => { if (!editing || saving) return; if (editing.status === "Antrian" && status === "Proses" && !before.length) { showToast("Foto BEFORE wajib diupload", "error"); return; } if (editing.status === "Proses" && status === "Selesai" && !after.length) { showToast("Foto AFTER wajib diupload", "error"); return; } setSaving(true); const payload: ServiceUpdatePayload = { status, catatan_kerusakan: note || undefined, teknisi: technician || undefined, estimasi_selesai: estimate || undefined, foto_before_urls: before.map((i) => i.secure_url), foto_after_urls: after.map((i) => i.secure_url) }; try { await Api.service.update(editing.service_id, payload); showToast("Service berhasil diupdate"); setEditing(null); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Update service gagal", "error"); } finally { setSaving(false); } };
  const visible = filter ? items.filter((item) => item.status === filter) : items; const options: ServiceStatus[] = user?.role === "teknisi" ? (editing?.status === "Antrian" ? ["Antrian","Proses","Ditolak"] : editing?.status === "Proses" ? ["Proses","Selesai","Ditolak"] : editing ? [editing.status] : ["Antrian","Proses","Selesai","Ditolak"]) : ["Antrian","Proses","Selesai","Approved","Ditolak"];
  return <div className="space-y-8"><div><h1 className="text-3xl font-semibold tracking-[-0.03em] text-jp-text dark:text-jp-text-dark">Data Service</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Workspace teknisi untuk memproses tiket</p></div><div className="flex flex-wrap gap-1.5">{["","Antrian","Proses","Selesai","Ditolak"].map((s) => <button type="button" key={s || "all"} onClick={() => setFilter(s)} className={`filter-tab rounded-xl px-4 py-2 ${filter === s ? "bg-jp-surface-subtle dark:bg-jp-surface-subtle-dark" : ""}`}>{s || "Semua"}</button>)}</div>{loading ? <LoadingSkeleton numberOfRows={5}/> : error ? <ErrorState message={error} onRetry={load}/> : visible.length ? <div className="space-y-3">{visible.map((s) => <div className="svc-card" key={s.service_id}><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="mb-1.5 flex flex-wrap items-center gap-2"><span className="text-[10px] text-jp-muted dark:text-jp-muted-dark">{s.service_id}</span><ServiceStatusBadge status={s.status as ServiceStatus}/></div><p className="font-semibold">{s.unit_label}</p><p className="font-mono text-[11px] text-jp-muted dark:text-jp-muted-dark">{s.unit_id}</p><p className="mt-1 text-sm text-jp-muted dark:text-jp-muted-dark">{s.keluhan}</p>{s.catatan_kerusakan && <p className="mt-1 text-[11px] italic text-jp-muted dark:text-jp-muted-dark">{s.catatan_kerusakan}</p>}<p className="mt-2 text-[11px] text-jp-muted dark:text-jp-muted-dark">{formatDateTimeShort(s.created_at)}</p></div>{((user?.role === "teknisi" && ["Antrian","Proses"].includes(s.status)) || user?.role === "owner") && <button type="button" className="btn-ghost" onClick={() => void openEdit(s.service_id)}>Update</button>}</div></div>)}</div> : <EmptyState message="Tidak ada tiket service" iconName="wrenchSvg"/>}
    <Modal isOpen={Boolean(editing)} onClose={() => { if (!saving) setEditing(null); }} title={editing ? `Update ${editing.service_id}` : "Update Service"} maxWidthClassName="max-w-2xl">{editing && <form className="space-y-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><LabelledSelect label="Status Pengerjaan" value={status} onChange={(e) => setStatus(e.target.value as ServiceStatus)}>{options.map((option) => <option key={option}>{option}</option>)}</LabelledSelect>{editing.status === "Antrian" && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 dark:border-emerald-500/20 dark:bg-emerald-500/10"><p className="mb-2 text-xs font-semibold text-emerald-600">Foto Before wajib sebelum mulai service</p><ImageUploader id="service-before" maxFiles={5} initialImages={before} folder="jayaphone/service/before" onChange={setBefore}/></div>}{editing.status === "Proses" && <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 dark:border-blue-500/20 dark:bg-blue-500/10"><p className="mb-2 text-xs font-semibold text-blue-600">Foto After wajib saat service selesai</p><ImageUploader id="service-after" maxFiles={5} initialImages={after} folder="jayaphone/service/after" onChange={setAfter}/></div>}<LabelledTextarea label="Catatan Kerusakan" rows={3} value={note} onChange={(e) => setNote(e.target.value)}/><LabelledInput label="Nama Teknisi" value={technician} onChange={(e) => setTechnician(e.target.value)}/><LabelledInput label="Estimasi Selesai" type="datetime-local" value={estimate} onChange={(e) => setEstimate(e.target.value)}/><button type="submit" disabled={saving} className="btn-primary w-full">{saving ? "Menyimpan..." : "Update Service"}</button></form>}</Modal>
  </div>;
}
