"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { LabelledInput, LabelledSelect, LabelledTextarea } from "@/components/ui/InputField";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import type { TransferStok, Unit } from "@/lib/types";
export default function TransferStokPage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast(); const [items, setItems] = useState<TransferStok[]>([]); const [filter, setFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [createOpen, setCreateOpen] = useState(false); const [responding, setResponding] = useState<TransferStok | null>(null); const [branches, setBranches] = useState<{ kode: string; nama: string }[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [target, setTarget] = useState(""); const [selectedUnits, setSelectedUnits] = useState<string[]>([]); const [note, setNote] = useState(""); const [decisionNote, setDecisionNote] = useState(""); const [decision, setDecision] = useState<"Diterima" | "Ditolak">("Diterima"); const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.transferStok.list({ status: filter || undefined })).data ?? []); } catch (e) { setError(e instanceof ApiError ? e.message : "Gagal memuat transfer stok"); } finally { setLoading(false); } }, [filter]); useEffect(() => { void load(); }, [load]);
  const openCreate = async () => { try { const [b,u] = await Promise.all([Api.transferStok.cabangList(), Api.units.list({ status: "Tersedia", cabang: user?.cabang, limit: 200 })]); setBranches((b.data ?? []).filter((branch) => branch.kode !== user?.cabang)); setUnits(u.data ?? []); setSelectedUnits([]); setTarget(""); setNote(""); setCreateOpen(true); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal memuat data transfer", "error"); } };
  const create = async () => { if (!target || !selectedUnits.length) { showToast("Pilih cabang tujuan dan minimal satu unit", "error"); return; } try { await Api.transferStok.create({ cabang_tujuan: target, unit_ids: selectedUnits.map((unit_id) => ({ unit_id })), catatan: note || undefined }); showToast("Transfer berhasil diajukan"); setCreateOpen(false); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal membuat transfer", "error"); } };
  const respond = async () => { if (!responding || (decision === "Ditolak" && !decisionNote.trim())) { showToast("Catatan wajib diisi jika transfer ditolak", "error"); return; } try { await Api.transferStok.respond(responding.transfer_id, { status: decision, catatan: decisionNote || undefined }); showToast(`Transfer ${decision.toLowerCase()}`); setResponding(null); setDecisionNote(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal memproses transfer", "error"); } };
  const visibleUnits = useMemo(() => units.filter((u) => `${u.unit_id} ${u.merk} ${u.tipe} ${u.storage}`.toLowerCase().includes(search.toLowerCase())), [units, search]); const canCreate = user?.role === "kepala_cabang"; const canRespond = user?.role === "owner" || user?.role === "kepala_cabang";
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">Transfer Stok Antar Cabang</h1><p className="text-xs text-zinc-400">Stok dipindahkan tanpa mengubah harga barang</p></div>{canCreate && <button type="button" className="btn-primary" onClick={() => void openCreate()}>+ Transfer Baru</button>}</div><div className="flex gap-2">{["","Pending","Diterima","Ditolak"].map((s) => <button type="button" key={s || "all"} className={`filter-tab rounded-xl px-3 py-2 ${filter === s ? "bg-zinc-100 dark:bg-zinc-800" : ""}`} onClick={() => setFilter(s)}>{s || "Semua"}</button>)}</div>{loading ? <LoadingSkeleton numberOfRows={5}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="table-wrap overflow-x-auto rounded-lg"><table className="w-full text-xs"><thead className="tbl-head border-b"><tr>{["ID Transfer","Dari → Ke","Jumlah","Unit","Status","Tanggal","Aksi"].map((h) => <th key={h} className="px-5 py-3.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{items.length ? items.map((t) => { const canAct = canRespond && t.status === "Pending" && (user?.role === "owner" || user?.cabang === t.cabang_tujuan); return <tr key={t.transfer_id} className="tbl-row"><td className="px-5 py-4 font-mono text-zinc-400">{t.transfer_id}</td><td className="px-5 py-4 font-medium">{t.cabang_asal} → {t.cabang_tujuan}</td><td className="px-5 py-4 text-center">{t.jumlah}</td><td className="px-5 py-4 text-zinc-400">{(t.units || []).slice(0,2).map((u) => u.unit_id_asal).join(", ")}{(t.units?.length || 0) > 2 ? ` +${(t.units?.length || 0)-2}` : ""}</td><td className="px-5 py-4"><span className={`badge ${t.status === "Diterima" ? "badge-tersedia" : t.status === "Ditolak" ? "badge-sold" : "badge-booking"}`}>{t.status}</span></td><td className="px-5 py-4 text-zinc-400">{t.created_at}</td><td className="px-5 py-4">{canAct ? <button type="button" className="btn-ghost" onClick={() => { setResponding(t); setDecision("Diterima"); setDecisionNote(""); }}>Proses</button> : <span className="text-zinc-400">—</span>}</td></tr>; }) : <tr><td colSpan={7}><EmptyState message="Belum ada transfer stok" iconName="packageSvg"/></td></tr>}</tbody></table></div>}
    <Modal isOpen={createOpen} onClose={() => setCreateOpen(false)} title="Transfer Stok ke Cabang Lain" maxWidthClassName="max-w-2xl"><div className="space-y-4"><LabelledSelect label="Cabang Tujuan" value={target} onChange={(e) => setTarget(e.target.value)}><option value="">Pilih cabang</option>{branches.map((b) => <option key={b.kode} value={b.kode}>{b.kode} — {b.nama}</option>)}</LabelledSelect><input className="w-full rounded-xl bg-zinc-100 p-2 text-xs outline-none dark:bg-zinc-900" placeholder="Cari unit..." value={search} onChange={(e) => setSearch(e.target.value)}/><div className="max-h-64 divide-y overflow-y-auto rounded-xl border border-divider">{visibleUnits.map((u) => <label key={u.unit_id} className="flex cursor-pointer items-center gap-3 p-3 text-xs hover:bg-zinc-50 dark:hover:bg-zinc-800"><input type="checkbox" checked={selectedUnits.includes(u.unit_id)} onChange={(e) => setSelectedUnits((current) => e.target.checked ? [...current, u.unit_id] : current.filter((id) => id !== u.unit_id))}/><span><strong>{u.merk} {u.tipe}</strong><small className="ml-2 text-zinc-400">{u.unit_id} · {u.storage}</small></span></label>)}</div><p className="text-[11px] text-zinc-400">{selectedUnits.length} unit dipilih</p><LabelledTextarea label="Catatan" rows={2} value={note} onChange={(e) => setNote(e.target.value)}/><button type="button" className="btn-primary w-full" onClick={() => void create()}>Kirim Transfer</button></div></Modal>
    <Modal isOpen={Boolean(responding)} onClose={() => setResponding(null)} title={responding ? `Proses ${responding.transfer_id}` : "Proses Transfer"}><div className="space-y-4"><p className="text-xs text-zinc-400">{responding?.cabang_asal} → {responding?.cabang_tujuan} · {responding?.jumlah} unit</p><div className="grid grid-cols-2 gap-3"><label className="rounded-xl border p-3 text-xs"><input type="radio" checked={decision === "Diterima"} onChange={() => setDecision("Diterima")}/> Terima</label><label className="rounded-xl border p-3 text-xs"><input type="radio" checked={decision === "Ditolak"} onChange={() => setDecision("Ditolak")}/> Tolak</label></div><LabelledTextarea label="Catatan" rows={3} value={decisionNote} onChange={(e) => setDecisionNote(e.target.value)}/><button type="button" className="btn-primary w-full" onClick={() => void respond()}>Simpan Keputusan</button></div></Modal>
  </div>;
}
