"use client";
import { useCallback, useEffect, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import type { InfluencerDashboardStats, Platform } from "@/lib/types";
import { DateFilterBar } from "@/components/ui/DateFilterBar";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { EmptyState } from "@/components/ui/EmptyState";
import { InfluencerTrendChart } from "./_components/InfluencerTrendChart";
import { createDefaultDateFilter, type DateFilterState } from "@/lib/utils/dateFilter";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import { formatCompactNumber } from "@/lib/utils/formatters";
const options: Array<{ value: Platform | ""; label: string }> = [{value:"",label:"Semua"},{value:"tiktok",label:"TikTok"},{value:"instagram",label:"Instagram"},{value:"youtube",label:"YouTube"}];
export default function InfluencerDashboardPage(): JSX.Element {
 const {user}=useAuth(); const {showToast}=useToast(); const [filter,setFilter]=useState<DateFilterState>(createDefaultDateFilter()); const [platform,setPlatform]=useState<Platform|"">(""); const [stats,setStats]=useState<InfluencerDashboardStats|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const days=filter.preset==="7d"?7:filter.preset==="1y"?365:filter.preset==="90d"?90:filter.start&&filter.end?Math.max(1,Math.ceil((new Date(filter.end).getTime()-new Date(filter.start).getTime())/86400000)+1):30;setStats((await Api.influencer.dashboard(days,platform||undefined)).data)}catch(e){const m=e instanceof ApiError?e.message:"Gagal memuat dashboard influencer";setError(m);showToast(m,"error")}finally{setLoading(false)}},[filter,platform,showToast]); useEffect(()=>{void load()},[load]);
 const n=formatCompactNumber;
 return <div className="jp-page"><div className="jp-page-header"><div><h1 className="jp-page-title">Dashboard Influencer</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Pantau performa konten dan produk yang dipromosikan · Cabang {user?.cabang||"-"}</p></div><div className="flex gap-2"><DateFilterBar currentFilterState={filter} onFilterStateChange={setFilter}/><select className="field-control w-full text-xs sm:w-auto" value={platform} onChange={e=>setPlatform(e.target.value as Platform|"")} aria-label="Filter platform">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div></div>{loading?<LoadingSkeleton numberOfRows={5}/>:error?<ErrorState message={error} onRetry={load}/>:stats&&<><div className="grid grid-cols-2 gap-4 lg:grid-cols-[1.618fr_1fr_1fr_1fr]">{[["Total Video",stats.total_video,"video dibuat"],["Total Views",stats.total_views,"penonton"],["Total Likes",stats.total_likes,"interaksi"],["Produk Dipromosikan",stats.produk_dipromosikan,"unit unik"]].map(([t,v,s])=><div key={String(t)} className="metric-card"><p className="label">{t}</p><p className="mt-1 text-3xl font-bold">{n(Number(v))}</p><p className="text-[11px] text-jp-muted dark:text-jp-muted-dark">{s}</p></div>)}</div><div className="section-panel p-6"><p className="mb-5 text-sm font-semibold">Trend Views</p><InfluencerTrendChart points={stats.trend_views||[]}/></div><div className="section-panel p-6"><p className="mb-5 text-xs font-medium uppercase tracking-widest text-jp-muted dark:text-jp-muted-dark">Top 5 Video Terbanyak Dilihat</p>{stats.top_videos?.length?<div className="space-y-3">{stats.top_videos.map((v,i)=><div key={v.video_id||v.unit_label+i} className="flex items-center gap-3 rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark"><span className="w-8 text-center font-bold text-jp-muted dark:text-jp-muted-dark">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{v.unit_label}</p><p className="text-sm text-jp-muted dark:text-jp-muted-dark capitalize">{v.platform} · {n(v.views)} views · {n(v.likes)} likes</p></div><span className="badge">{v.platform}</span></div>)}</div>:<EmptyState message="Belum ada video" iconName="filmSvg"/>}</div></>}</div>
}