"use client";
import { useCallback, useEffect, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import type { InfluencerDashboardStats, Platform } from "@/lib/types";
import { DateFilterBar } from "@/components/ui/DateFilterBar";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { EmptyState } from "@/components/ui/EmptyState";
import { createDefaultDateFilter, type DateFilterState } from "@/lib/utils/dateFilter";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
const options: Array<{ value: Platform | ""; label: string }> = [{value:"",label:"Semua"},{value:"tiktok",label:"TikTok"},{value:"instagram",label:"Instagram"},{value:"youtube",label:"YouTube"}];
export default function InfluencerDashboardPage(): JSX.Element {
 const {user}=useAuth(); const {showToast}=useToast(); const [filter,setFilter]=useState<DateFilterState>(createDefaultDateFilter()); const [platform,setPlatform]=useState<Platform|"">(""); const [stats,setStats]=useState<InfluencerDashboardStats|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const days=filter.preset==="7d"?7:filter.preset==="1y"?365:filter.preset==="90d"?90:filter.start&&filter.end?Math.max(1,Math.ceil((new Date(filter.end).getTime()-new Date(filter.start).getTime())/86400000)+1):30;setStats((await Api.influencer.dashboard(days,platform||undefined)).data)}catch(e){const m=e instanceof ApiError?e.message:"Gagal memuat dashboard influencer";setError(m);showToast(m,"error")}finally{setLoading(false)}},[filter,platform,showToast]); useEffect(()=>{void load()},[load]);
 const n=(v:number)=>(v||0).toLocaleString("id-ID"); const max=Math.max(...(stats?.trend_views||[]).map(x=>x.views),1);
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">Dashboard Influencer</h1><p className="text-xs text-zinc-400">Cabang {user?.cabang||"-"}</p></div><div className="flex gap-2"><DateFilterBar currentFilterState={filter} onFilterStateChange={setFilter}/><select className="rounded-xl bg-zinc-100 px-3 py-2 text-xs dark:bg-zinc-900" value={platform} onChange={e=>setPlatform(e.target.value as Platform|"")} aria-label="Filter platform">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div></div>{loading?<LoadingSkeleton numberOfRows={5}/>:error?<ErrorState message={error} onRetry={load}/>:stats&&<><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Total Video",stats.total_video,"video dibuat"],["Total Views",stats.total_views,"penonton"],["Total Likes",stats.total_likes,"interaksi"],["Produk Dipromosikan",stats.produk_dipromosikan,"unit unik"]].map(([t,v,s])=><div key={String(t)} className="panel rounded-lg p-5"><p className="label">{t}</p><p className="mt-1 text-3xl font-bold">{n(Number(v))}</p><p className="text-[11px] text-zinc-400">{s}</p></div>)}</div><div className="panel rounded-lg p-6"><p className="text-sm font-semibold">Trend Views</p><div className="mt-5 flex h-56 items-end gap-2">{stats.trend_views?.length?stats.trend_views.map((p,i)=><div key={p.tanggal||p.minggu||i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-brand-teal" style={{height:`${Math.max(5,p.views/max*100)}%`}} title={`${n(p.views)} views`}/><span className="max-w-full truncate text-[9px] text-zinc-400">{p.tanggal||p.minggu||"-"}</span></div>):<div className="flex w-full items-center justify-center"><EmptyState message="Belum ada data video" iconName="chartSvg"/></div>}</div></div><div className="panel rounded-lg p-6"><p className="mb-5 text-xs font-medium uppercase tracking-widest text-zinc-400">Top 5 Video Terbanyak Dilihat</p>{stats.top_videos?.length?<div className="space-y-3">{stats.top_videos.map((v,i)=><div key={v.video_id||v.unit_label+i} className="flex items-center gap-3 rounded-xl bg-zinc-100/50 p-3 dark:bg-zinc-800/50"><span className="w-8 text-center font-bold text-zinc-400">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{v.unit_label}</p><p className="text-xs text-zinc-400 capitalize">{v.platform} · {n(v.views)} views · {n(v.likes)} likes</p></div><span className="badge">{v.platform}</span></div>)}</div>:<EmptyState message="Belum ada video" iconName="filmSvg"/>}</div></>}</div>
}