"use client";
import { useCallback, useEffect, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import type { CODRequest, CODStatus } from "@/lib/types";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { LabelledInput, LabelledSelect, LabelledTextarea } from "@/components/ui/InputField";
import { ImageUploader } from "@/components/ui/ImageUploader";
import { useToast } from "@/contexts/ToastContext";
const labels: Record<string, string> = { menunggu_kurir: "Menunggu kurir", diterima: "Diterima", kurir_menuju_lokasi: "Menuju lokasi penjual", sudah_bertemu_penjual: "Sudah bertemu", barang_akan_dijemput: "Akan dijemput", barang_sudah_diambil: "Barang diambil", kurir_menuju_toko: "Menuju toko", sedang_diantar: "Sedang diantar", terkirim: "Terkirim", kurir_sedang_transaksi: "Sedang transaksi", transaksi_berhasil: "Transaksi berhasil", menunggu_approval_kasir: "Menunggu approval", selesai: "Selesai", ditolak: "Ditolak", gagal: "Gagal" };
type UnitDraft = { imei: string; merk: string; tipe: string; storage: string; ram: string; warna: string; battery: number; kondisi_hp: "Mulus" | "Repair"; kondisi: string; catatan: string; foto_url?: string };
export default function KurirDashboardPage(): JSX.Element { const { showToast } = useToast(); const [items, setItems] = useState<CODRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<CODRequest | null>(null); const [rejectReason, setRejectReason] = useState(""); const [unit, setUnit] = useState<UnitDraft>({ imei: "", merk: "", tipe: "", storage: "-", ram: "-", warna: "-", battery: 100, kondisi_hp: "Mulus", kondisi: "BN", catatan: "" }); const [foto, setFoto] = useState<string[]>([]); const [deal, setDeal] = useState(""); const [tab, setTab] = useState<"tugas" | "riwayat">("tugas");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.cod.kurirDashboard({ limit: 25 })).data ?? []); } catch (e) { setError(e instanceof ApiError ? e.message : "Gagal memuat dashboard kurir"); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const status = async (item: CODRequest, next: CODStatus, note?: string): Promise<void> => { try { await Api.cod.kurirUpdateStatus(item.cod_id, next, note); showToast(`Status diperbarui: ${labels[next] || next}`); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Status gagal diperbarui", "error"); } };
  const accept = async (item: CODRequest): Promise<void> => { try { await Api.cod.kurirAccept(item.cod_id); showToast("COD diterima"); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal menerima COD", "error"); } };
  const reject = async (item: CODRequest): Promise<void> => { if (!rejectReason.trim()) { showToast("Alasan reject wajib diisi", "error"); return; } try { await Api.cod.kurirRejectBeli(item.cod_id, rejectReason.trim()); showToast("COD ditolak"); setSelected(null); setRejectReason(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal menolak COD", "error"); } };
  const submitBeli = async (): Promise<void> => { if (!selected || !Number(deal) || !unit.imei || !unit.merk || !unit.tipe) { showToast("Harga deal dan data unit wajib diisi", "error"); return; } try { await Api.cod.kurirSubmitBeli(selected.cod_id, { deal_price: Number(deal), unit_data: { ...unit, foto_url: foto[0] } }); showToast("Data COD beli dikirim untuk approval"); setSelected(null); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Submit COD beli gagal", "error"); } };
  const openUnit = (item: CODRequest): void => { setSelected(item); setDeal(String(item.offer_price || "")); setFoto([]); };
  const update = (key: keyof UnitDraft, value: string | number): void => setUnit((old) => ({ ...old, [key]: value }));
  const terminalStatuses = new Set(["transaksi_berhasil", "terkirim", "selesai", "ditolak", "gagal"]); const visibleItems = items.filter((item) => tab === "riwayat" ? terminalStatuses.has(item.status) : !terminalStatuses.has(item.status));
  const action = (item: CODRequest): JSX.Element => { if (item.status === "menunggu_kurir") return <><button type="button" className="btn-primary mr-2" onClick={() => void accept(item)}>Accept</button><button type="button" className="btn-error" onClick={() => { setSelected(item); setRejectReason(""); }}>Reject</button></>; if (item.status === "diterima") return <button type="button" className="btn-primary" onClick={() => void status(item, item.type === "beli" ? "kurir_menuju_lokasi" : item.type === "delivery" ? "kurir_menuju_toko" : "barang_akan_dijemput")}>Mulai Tugas</button>; if (item.status === "barang_akan_dijemput" || item.status === "kurir_menuju_toko") return <button type="button" className="btn-primary" onClick={() => void status(item, "barang_sudah_diambil")}>Barang Sudah Diambil</button>; if (item.status === "kurir_menuju_lokasi") return <button type="button" className="btn-primary" onClick={() => void status(item, "sudah_bertemu_penjual")}>Sudah Bertemu</button>; if (item.status === "sudah_bertemu_penjual" && item.type === "beli") return <button type="button" className="btn-primary" onClick={() => openUnit(item)}>Submit Data Beli</button>; if (item.status === "barang_sudah_diambil" && item.type === "delivery") return <button type="button" className="btn-primary" onClick={() => void status(item, "sedang_diantar")}>Mulai Antar</button>; if (item.status === "sedang_diantar") return <><button type="button" className="btn-success mr-2" onClick={() => void status(item, "terkirim")}>Terkirim</button><button type="button" className="btn-error" onClick={() => void status(item, "gagal")}>Gagal</button></>; if (item.status === "barang_sudah_diambil" && item.type === "jual") return <button type="button" className="btn-primary" onClick={() => void status(item, "kurir_sedang_transaksi")}>Mulai Transaksi</button>; if (item.status === "kurir_sedang_transaksi") return <><button type="button" className="btn-success mr-2" onClick={() => void status(item, "transaksi_berhasil")}>Berhasil</button><button type="button" className="btn-error" onClick={() => void status(item, "gagal")}>Gagal</button></>; return <span className="text-jp-muted dark:text-jp-muted-dark">{labels[item.status] || item.status}</span>; };
  return <div className="space-y-8"><div><h1 className="text-3xl font-semibold tracking-[-0.03em] text-jp-text dark:text-jp-text-dark">Dashboard Kurir</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Kelola tugas COD beli, jual, dan delivery</p></div><div className="flex gap-2"><button type="button" className={`btn-ghost ${tab === "tugas" ? "bg-jp-surface-subtle" : ""}`} onClick={() => setTab("tugas")}>Tugas aktif</button><button type="button" className={`btn-ghost ${tab === "riwayat" ? "bg-jp-surface-subtle" : ""}`} onClick={() => setTab("riwayat")}>Riwayat</button></div>{loading ? <LoadingSkeleton numberOfRows={5}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="table-wrap overflow-x-auto rounded-2xl"><table className="w-full text-xs"><thead className="tbl-head"><tr>{["Waktu","Tipe","Detail","Lokasi","Status","Aksi"].map((h) => <th key={h} className="px-5 py-3.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{visibleItems.length ? visibleItems.map((item) => <tr key={item.cod_id} className="tbl-row"><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{item.created_at}</td><td className="px-5 py-4"><span className="badge">{item.type}</span></td><td className="px-5 py-4 font-medium">{item.product_name || item.trx_id || item.items?.map((x) => x.nama).join(", ") || "COD"}</td><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{item.location || item.delivery_address || "-"}</td><td className="px-5 py-4"><span className="badge">{labels[item.status] || item.status}</span></td><td className="px-5 py-4 whitespace-nowrap">{action(item)}</td></tr>) : <tr><td colSpan={6}><EmptyState message={tab === "riwayat" ? "Belum ada riwayat COD" : "Belum ada tugas COD"} iconName="truckSvg"/></td></tr>}</tbody></table></div>}
    <Modal isOpen={Boolean(selected) && selected?.status === "sudah_bertemu_penjual"} onClose={() => setSelected(null)} title="Submit COD Beli" maxWidthClassName="max-w-3xl"><div className="space-y-3"><div className="grid grid-cols-2 gap-3"><LabelledInput label="Harga Deal (Rp)" type="number" value={deal} onChange={(e) => setDeal(e.target.value)}/><LabelledInput label="Merk" required value={unit.merk} onChange={(e) => update("merk", e.target.value)}/><LabelledInput label="Tipe" required value={unit.tipe} onChange={(e) => update("tipe", e.target.value)}/><LabelledInput label="IMEI" required value={unit.imei} onChange={(e) => update("imei", e.target.value)}/><LabelledInput label="Storage" value={unit.storage} onChange={(e) => update("storage", e.target.value)}/><LabelledInput label="RAM" value={unit.ram} onChange={(e) => update("ram", e.target.value)}/><LabelledInput label="Warna" value={unit.warna} onChange={(e) => update("warna", e.target.value)}/><LabelledSelect label="Kondisi HP" value={unit.kondisi_hp} onChange={(e) => update("kondisi_hp", e.target.value)}><option>Mulus</option><option>Repair</option></LabelledSelect><LabelledInput label="Battery %" type="number" value={unit.battery} onChange={(e) => update("battery", Number(e.target.value))}/></div><LabelledTextarea label="Catatan" rows={2} value={unit.catatan} onChange={(e) => update("catatan", e.target.value)}/><ImageUploader id="kurir-unit-foto" maxFiles={5} folder="jayaphone/units/cod-beli" onChange={(images) => setFoto(images.map((image) => image.secure_url))}/><button type="button" className="btn-primary w-full" onClick={() => void submitBeli()}>Kirim untuk Approval</button></div></Modal>
    <Modal isOpen={Boolean(selected) && selected?.status === "menunggu_kurir"} onClose={() => setSelected(null)} title="Reject COD"><div className="space-y-3"><LabelledTextarea label="Alasan" rows={3} value={rejectReason} onChange={(e) => setRejectReason(e.target.value)}/><button type="button" className="btn-error w-full" onClick={() => selected && void reject(selected)}>Reject COD</button></div></Modal></div>;
}
