"use client";

import { useEffect, useMemo, useState } from "react";
import { Api } from "@/lib/api";
import { DateFilterBar } from "@/components/ui/DateFilterBar";
import { ErrorState } from "@/components/ui/ErrorState";
import { EmptyState } from "@/components/ui/EmptyState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { PhotoGallery } from "@/components/ui/PhotoGallery";
import { ServiceStatusBadge } from "@/components/ui/Badge";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import { useApiList } from "@/hooks/useApiList";
import { createDefaultDateFilter, toApiQueryParams } from "@/lib/utils/dateFilter";
import { formatDateTimeShort } from "@/lib/utils/formatters";
import type { Cabang, ServiceStatus, ServiceTicket } from "@/lib/types";

export default function ServicePage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast(); const [filter, setFilter] = useState(createDefaultDateFilter); const [branch, setBranch] = useState(""); const [status, setStatus] = useState(""); const [branches, setBranches] = useState<Cabang[]>([]); const [detail, setDetail] = useState<(ServiceTicket & { timeline?: { event: string; waktu: string }[] }) | null>(null); const [approveUnit, setApproveUnit] = useState<string | null>(null); const [salePrice, setSalePrice] = useState("");
  const params = useMemo(() => ({ limit: 50, ...toApiQueryParams(filter), ...(branch ? { cabang: branch } : {}), ...(status ? { status } : {}) }), [filter, branch, status]);
  const { items, loading, error, reload: load } = useApiList<ServiceTicket>(() => Api.service.list(params).then((r) => r.data ?? []), [params], "Gagal memuat service");
  useEffect(() => { if (user?.role === "owner") void Api.cabang.list().then((r) => setBranches(r.data ?? [])).catch(() => undefined); }, [user?.role]);
  const openDetail = async (id: string) => { try { setDetail((await Api.service.detail(id)).data); } catch (e) { showToast(e instanceof Error ? e.message : "Detail service gagal", "error"); } };
  return <div className="jp-page"><div className="jp-page-header"><div><h1 className="jp-page-title">Data Service</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">{items.length} tiket service</p></div><div className="flex flex-wrap gap-2"><DateFilterBar currentFilterState={filter} onFilterStateChange={setFilter}/>{user?.role === "owner" && <select className="field-control w-full text-xs sm:w-auto" value={branch} onChange={(e) => setBranch(e.target.value)}><option value="">Semua Cabang</option>{branches.map((b) => <option key={b.kode} value={b.kode}>{b.nama}</option>)}</select>}<select className="field-control w-full text-xs sm:w-auto" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Semua Status</option>{["Antrian","Proses","Selesai","Approved","Ditolak"].map((s) => <option key={s}>{s}</option>)}</select></div></div>{loading ? <LoadingSkeleton numberOfRows={6}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="table-wrap overflow-x-auto rounded-jp-md"><table className="w-full text-xs"><thead className="tbl-head border-b"><tr>{["ID","Unit","Keluhan","Teknisi","Status","Masuk","Aksi"].map((h) => <th key={h} className={`px-5 py-3.5 text-left font-medium ${h === "Aksi" ? "tbl-action-col" : ""}`}>{h}</th>)}</tr></thead><tbody>{items.length ? items.map((s) => <tr key={s.service_id} className="tbl-row"><td className="px-5 py-4 font-mono text-jp-muted dark:text-jp-muted-dark">{s.service_id}</td><td className="px-5 py-4"><p className="font-medium">{s.unit_label}</p><p className="text-[10px] text-jp-muted dark:text-jp-muted-dark">{s.unit_id}</p></td><td className="max-w-[180px] truncate px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{s.keluhan}</td><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{s.teknisi || "—"}</td><td className="px-5 py-4"><ServiceStatusBadge status={s.status as ServiceStatus}/></td><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{formatDateTimeShort(s.created_at)}</td><td className="tbl-action-col px-5 py-4"><div className="flex flex-wrap gap-1.5"><button type="button" className="btn-ghost" onClick={() => void openDetail(s.service_id)}>Detail</button>{s.status === "Selesai" && <button type="button" className="btn-success" onClick={() => { setApproveUnit(s.unit_id); setSalePrice(""); }}>Approve</button>}</div></td></tr>) : <tr><td colSpan={7}><EmptyState message="Belum ada data service" iconName="wrenchSvg"/></td></tr>}</tbody></table></div>}
    <Modal isOpen={Boolean(approveUnit)} onClose={() => setApproveUnit(null)} title="Approve Repair"><div className="space-y-5"><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Masukkan harga jual unit setelah repair.</p><input className="w-full rounded-jp-sm bg-jp-surface-subtle p-2 text-sm outline-none dark:bg-jp-surface-subtle-dark" type="number" min={0} value={salePrice} onChange={(e) => setSalePrice(e.target.value)} placeholder="Harga jual"/><div className="flex gap-2"><button type="button" className="btn-ghost flex-1" onClick={() => setApproveUnit(null)}>Batal</button><button type="button" className="btn-success flex-1" disabled={!salePrice || Number(salePrice) <= 0} onClick={async () => { if (!approveUnit) return; try { await Api.units.approveRepair(approveUnit, { harga_jual: Number(salePrice) }); setApproveUnit(null); showToast("Repair disetujui"); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Approval gagal", "error"); } }}>Simpan Approval</button></div></div></Modal>
    <Modal isOpen={Boolean(detail)} onClose={() => setDetail(null)} title={detail ? `Detail ${detail.service_id}` : "Detail Service"} maxWidthClassName="max-w-2xl">{detail && <div className="space-y-5 text-xs"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark"><span className="text-jp-muted dark:text-jp-muted-dark">Unit</span><p className="mt-1 font-medium">{detail.unit_label}</p></div><div className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark"><span className="text-jp-muted dark:text-jp-muted-dark">Customer</span><p className="mt-1 font-medium">{detail.nama_customer}</p></div><div className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark"><span className="text-jp-muted dark:text-jp-muted-dark">Status</span><div className="mt-1"><ServiceStatusBadge status={detail.status as ServiceStatus}/></div></div><div className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark"><span className="text-jp-muted dark:text-jp-muted-dark">Teknisi</span><p className="mt-1 font-medium">{detail.teknisi || "—"}</p></div></div><div><p className="mb-1 font-semibold">Keluhan</p><p className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark">{detail.keluhan}</p></div>{detail.catatan_kerusakan && <div><p className="mb-1 font-semibold">Catatan Kerusakan</p><p className="rounded-jp-sm bg-jp-surface-subtle p-3 dark:bg-jp-surface-subtle-dark">{detail.catatan_kerusakan}</p></div>}<div className="grid gap-4 sm:grid-cols-2"><PhotoGallery images={detail.foto_before_urls || []} label="Foto Before"/><PhotoGallery images={detail.foto_after_urls || []} label="Foto After"/></div><button type="button" className="btn-ghost w-full" onClick={() => setDetail(null)}>Tutup</button></div>}</Modal>
  </div>;
}
