"use client";
import { useCallback, useEffect, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { LabelledInput, LabelledSelect, LabelledTextarea } from "@/components/ui/InputField";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import type { RequestSparepart } from "@/lib/types";
export default function RequestSparepartPage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast(); const [items, setItems] = useState<RequestSparepart[]>([]); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState<RequestSparepart | null>(null); const [type, setType] = useState("SPAREPART"); const [name, setName] = useState(""); const [quantity, setQuantity] = useState("1"); const [serviceId, setServiceId] = useState(""); const [spId, setSpId] = useState(""); const [note, setNote] = useState(""); const [estimate, setEstimate] = useState(""); const [price, setPrice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.requestSparepart.list({ status: status || undefined })).data ?? []); } catch (e) { setError(e instanceof ApiError ? e.message : "Gagal memuat request sparepart"); } finally { setLoading(false); } }, [status]); useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!name.trim() || Number(quantity) <= 0) { showToast("Nama sparepart dan jumlah wajib diisi", "error"); return; } try { await Api.requestSparepart.create({ tipe: type, service_id: serviceId || undefined, sp_id: spId || undefined, nama_sp: name.trim(), jumlah: Number(quantity), keterangan: note || undefined, cabang: user?.cabang || "JYP" }); showToast("Request sparepart berhasil dibuat"); setFormOpen(false); setName(""); setQuantity("1"); setNote(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Request gagal dibuat", "error"); } };
  const respond = async (decision: "Disetujui" | "Ditolak") => { if (!selected) return; if (decision === "Ditolak" && !note.trim()) { showToast("Catatan wajib diisi saat menolak", "error"); return; } try { if (decision === "Disetujui") await Api.requestSparepart.approve(selected.id, { harga_jual: Number(price) || 0, status: decision, catatan: note || undefined }); else await Api.requestSparepart.respond(selected.id, { status: decision, estimasi_tiba: estimate || undefined, catatan: note || undefined }); showToast(`Request ${decision.toLowerCase()}`); setSelected(null); setNote(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Aksi request gagal", "error"); } };
  const canCreate = ["teknisi","kasir","kepala_cabang"].includes(user?.role || ""); const canApprove = ["kasir","kepala_cabang","owner"].includes(user?.role || "");
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">Request Sparepart</h1><p className="text-xs text-zinc-400">Permintaan sparepart untuk service dan stok</p></div>{canCreate && <button type="button" className="btn-primary" onClick={() => setFormOpen(true)}>+ Request Baru</button>}</div><div className="flex gap-2">{["","Pending","Disetujui","Ditolak","Selesai"].map((s) => <button type="button" key={s || "all"} className={`filter-tab rounded-xl px-3 py-2 ${status === s ? "bg-zinc-100 dark:bg-zinc-800" : ""}`} onClick={() => setStatus(s)}>{s || "Semua"}</button>)}</div>{loading ? <LoadingSkeleton numberOfRows={5}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="table-wrap overflow-x-auto rounded-lg"><table className="w-full text-xs"><thead className="tbl-head border-b"><tr>{["Request","Sparepart","Tipe","Jumlah","Cabang","Status","Aksi"].map((h) => <th key={h} className="px-5 py-3.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{items.length ? items.map((r) => <tr key={r.id} className="tbl-row"><td className="px-5 py-4 font-mono text-zinc-400">{r.id}</td><td className="px-5 py-4"><p className="font-medium">{r.nama_sp}</p><p className="text-[10px] text-zinc-400">{r.sp_id || "Custom"}</p></td><td className="px-5 py-4 text-zinc-400">{r.tipe}</td><td className="px-5 py-4">{r.jumlah}</td><td className="px-5 py-4 text-zinc-400">{r.cabang}</td><td className="px-5 py-4"><span className="badge badge-booking">{r.status}</span></td><td className="px-5 py-4">{canApprove && ["Pending","Menunggu_Kasir"].includes(r.status) ? <button type="button" className="btn-ghost" onClick={() => { setSelected(r); setPrice(""); setEstimate(""); setNote(""); }}>Proses</button> : <span className="text-zinc-400">—</span>}</td></tr>) : <tr><td colSpan={7}><EmptyState message="Belum ada request sparepart" iconName="packageSvg"/></td></tr>}</tbody></table></div>}
    <Modal isOpen={formOpen} onClose={() => setFormOpen(false)} title="Request Sparepart"><div className="space-y-3"><LabelledSelect label="Tipe" value={type} onChange={(e) => setType(e.target.value)}><option>SPAREPART</option><option>Servis</option><option>Barang</option></LabelledSelect><LabelledInput label="Nama Sparepart" value={name} onChange={(e) => setName(e.target.value)}/><div className="grid grid-cols-2 gap-3"><LabelledInput label="SP ID (opsional)" value={spId} onChange={(e) => setSpId(e.target.value)}/><LabelledInput label="Jumlah" type="number" min={1} value={quantity} onChange={(e) => setQuantity(e.target.value)}/></div><LabelledInput label="Service ID (opsional)" value={serviceId} onChange={(e) => setServiceId(e.target.value)}/><LabelledTextarea label="Keterangan" rows={3} value={note} onChange={(e) => setNote(e.target.value)}/><button type="button" className="btn-primary w-full" onClick={() => void create()}>Kirim Request</button></div></Modal>
    <Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title={selected ? `Proses ${selected.id}` : "Proses Request"}><div className="space-y-3"><p className="text-xs text-zinc-400">{selected?.nama_sp} · {selected?.jumlah} unit</p><LabelledInput label="Harga Jual" type="number" value={price} onChange={(e) => setPrice(e.target.value)}/><LabelledInput label="Estimasi Tiba" type="date" value={estimate} onChange={(e) => setEstimate(e.target.value)}/><LabelledTextarea label="Catatan" rows={3} value={note} onChange={(e) => setNote(e.target.value)}/><div className="flex gap-2"><button type="button" className="btn-error flex-1" onClick={() => void respond("Ditolak")}>Tolak</button><button type="button" className="btn-success flex-1" onClick={() => void respond("Disetujui")}>Setujui</button></div></div></Modal>
  </div>;
}
