"use client";

import { useMemo, useState } from "react";
import { Api } from "@/lib/api";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { LabelledInput, LabelledSelect, LabelledTextarea } from "@/components/ui/InputField";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import { useApiList } from "@/hooks/useApiList";
import { formatRupiah } from "@/lib/utils/formatters";
import type { Sparepart } from "@/lib/types";

export default function SparepartPage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast(); const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [formOpen, setFormOpen] = useState(false); const [stockItem, setStockItem] = useState<Sparepart | null>(null); const [name, setName] = useState(""); const [cat, setCat] = useState("Aksesoris"); const [buy, setBuy] = useState(""); const [sell, setSell] = useState(""); const [stock, setStock] = useState("1"); const [delta, setDelta] = useState(""); const [note, setNote] = useState("");
  const { items, loading, error, reload: load } = useApiList<Sparepart>(() => Api.sparepart.list({ kategori: category || undefined }).then((r) => r.data ?? []), [category], "Gagal memuat sparepart");
  const visible = useMemo(() => items.filter((s) => `${s.nama} ${s.sp_id} ${s.kategori}`.toLowerCase().includes(query.toLowerCase())), [items, query]); const create = async () => { if (!name.trim() || Number(sell) <= 0) { showToast("Nama dan harga jual wajib diisi", "error"); return; } try { await Api.sparepart.create({ nama: name.trim(), kategori: cat, satuan: "pcs", harga_beli: Number(buy) || 0, harga_jual: Number(sell), stok: Number(stock) || 0, cabang: user?.cabang || "JYP" }); showToast("Sparepart berhasil ditambahkan"); setFormOpen(false); setName(""); setBuy(""); setSell(""); setStock("1"); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal menambah sparepart", "error"); } }; const updateStock = async () => { if (!stockItem || !delta) return; try { await Api.sparepart.updateStok(stockItem.sp_id, { delta: Number(delta), catatan: note || undefined }); showToast("Stok sparepart diperbarui"); setStockItem(null); setDelta(""); setNote(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal memperbarui stok", "error"); } };
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-semibold tracking-[-0.03em] text-jp-text dark:text-jp-text-dark">Sparepart</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Master sparepart dan stok cabang</p></div><button type="button" className="btn-primary" onClick={() => setFormOpen(true)}>+ Tambah Sparepart</button></div><div className="flex flex-wrap gap-2"><input className="w-full max-w-sm rounded-xl border border-jp-border bg-jp-surface-subtle dark:border-jp-border-dark p-2 text-xs outline-none dark:bg-jp-surface-subtle-dark" placeholder="Cari sparepart..." value={query} onChange={(e) => setQuery(e.target.value)}/><input className="rounded-xl border border-jp-border bg-jp-surface-subtle dark:border-jp-border-dark p-2 text-xs outline-none dark:bg-jp-surface-subtle-dark" placeholder="Kategori" value={category} onChange={(e) => setCategory(e.target.value)}/></div>{loading ? <LoadingSkeleton numberOfRows={5}/> : error ? <ErrorState message={error} onRetry={load}/> : <div className="table-wrap overflow-x-auto rounded-2xl"><table className="w-full text-xs"><thead className="tbl-head border-b"><tr>{["ID","Nama","Kategori","Cabang","Stok","Harga Beli","Harga Jual","Aksi"].map((h) => <th key={h} className={`px-5 py-3.5 text-left font-medium ${h === "Aksi" ? "tbl-action-col" : ""}`}>{h}</th>)}</tr></thead><tbody>{visible.length ? visible.map((s) => <tr key={s.sp_id} className="tbl-row"><td className="px-5 py-4 font-mono text-jp-muted dark:text-jp-muted-dark">{s.sp_id}</td><td className="px-5 py-4 font-medium">{s.nama}</td><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{s.kategori}</td><td className="px-5 py-4 text-jp-muted dark:text-jp-muted-dark">{s.cabang}</td><td className={`px-5 py-4 font-semibold ${s.stok <= 0 ? "text-red-400" : "font-mono text-jp-text dark:text-jp-text-dark"}`}>{s.stok} {s.satuan}</td><td className="px-5 py-4">{formatRupiah(s.harga_beli)}</td><td className="px-5 py-4">{formatRupiah(s.harga_jual)}</td><td className="tbl-action-col px-5 py-4"><button type="button" className="btn-ghost" onClick={() => setStockItem(s)}>Update Stok</button></td></tr>) : <tr><td colSpan={8}><EmptyState message="Belum ada sparepart" iconName="wrenchSvg"/></td></tr>}</tbody></table></div>}
    <Modal isOpen={formOpen} onClose={() => setFormOpen(false)} title="Tambah Sparepart"><div className="space-y-3"><LabelledInput label="Nama" value={name} onChange={(e) => setName(e.target.value)}/><LabelledInput label="Kategori" value={cat} onChange={(e) => setCat(e.target.value)}/><div className="grid grid-cols-2 gap-3"><LabelledInput label="Harga Beli" type="number" value={buy} onChange={(e) => setBuy(e.target.value)}/><LabelledInput label="Harga Jual" type="number" value={sell} onChange={(e) => setSell(e.target.value)}/></div><LabelledInput label="Stok Awal" type="number" min={0} value={stock} onChange={(e) => setStock(e.target.value)}/><div className="flex gap-2"><button type="button" className="btn-ghost flex-1" onClick={() => setFormOpen(false)}>Batal</button><button type="button" className="btn-primary flex-1" onClick={() => void create()}>Simpan</button></div></div></Modal>
    <Modal isOpen={Boolean(stockItem)} onClose={() => setStockItem(null)} title={stockItem ? `Update Stok ${stockItem.nama}` : "Update Stok"}><div className="space-y-3"><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Gunakan angka positif untuk menambah, negatif untuk mengurangi.</p><LabelledInput label="Perubahan Stok" type="number" value={delta} onChange={(e) => setDelta(e.target.value)} placeholder="+10 atau -2"/><LabelledTextarea label="Catatan" rows={3} value={note} onChange={(e) => setNote(e.target.value)}/><button type="button" className="btn-primary w-full" onClick={() => void updateStock()}>Simpan Perubahan</button></div></Modal>
  </div>;
}
