"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Api, ApiError } from "@/lib/api";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingSkeleton } from "@/components/ui/LoadingSkeleton";
import { Modal } from "@/components/ui/Modal";
import { LabelledInput, LabelledTextarea } from "@/components/ui/InputField";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/contexts/ToastContext";
import type { Customer } from "@/lib/types";

export default function CustomersPage(): JSX.Element {
  const { user } = useAuth(); const { showToast } = useToast();
  const [items, setItems] = useState<Customer[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [addOpen, setAddOpen] = useState(false); const [rejecting, setRejecting] = useState<Customer | null>(null);
  const [name, setName] = useState(""); const [contact, setContact] = useState(""); const [reason, setReason] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await Api.customer.list({ status: status || undefined })).data ?? []); } catch (e) { setError(e instanceof ApiError ? e.message : "Gagal memuat customer"); } finally { setLoading(false); } }, [status]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter((c) => `${c.nama} ${c.kontak} ${c.cabang}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const isApprover = user?.role === "owner" || user?.role === "kepala_cabang";
  const create = async () => { if (!name.trim() || !contact.trim()) { showToast("Nama dan kontak wajib diisi", "error"); return; } try { await Api.customer.create({ nama: name.trim(), kontak: contact.trim(), cabang: user?.cabang || "JYP" }); showToast("Customer berhasil ditambahkan"); setName(""); setContact(""); setAddOpen(false); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Gagal menambah customer", "error"); } };
  const action = async (kind: "approve" | "reject" | "resubmit", customer: Customer) => { try { if (kind === "approve") await Api.customer.approve(customer.id); else if (kind === "reject") { if (!reason.trim()) { showToast("Alasan reject wajib diisi", "error"); return; } await Api.customer.reject(customer.id, reason.trim()); } else await Api.customer.resubmit(customer.id); showToast(kind === "approve" ? "Customer disetujui" : kind === "reject" ? "Customer ditolak" : "Customer diajukan ulang"); setRejecting(null); setReason(""); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Aksi customer gagal", "error"); } };
  return <div className="space-y-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-semibold tracking-[-0.03em] text-jp-text dark:text-jp-text-dark">Data Customer</h1><p className="text-sm text-jp-muted dark:text-jp-muted-dark">Kelola customer dan status verifikasi</p></div><button type="button" className="btn-primary" onClick={() => setAddOpen(true)}>+ Tambah Customer</button></div><div className="flex flex-wrap gap-2"><input className="search-field w-full max-w-sm rounded-xl bg-jp-surface-subtle p-2 text-xs outline-none dark:bg-jp-surface-subtle-dark" placeholder="Cari nama, kontak, cabang..." value={query} onChange={(e) => setQuery(e.target.value)} /><select className="rounded-xl bg-jp-surface-subtle px-3 py-2 text-xs dark:bg-jp-surface-subtle-dark" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Semua Status</option><option value="Pending">Pending</option><option value="Verified">Verified</option><option value="Rejected">Rejected</option></select></div>{loading ? <LoadingSkeleton numberOfRows={5} /> : error ? <ErrorState message={error} onRetry={load} /> : <div className="table-wrap overflow-x-auto rounded-2xl"><table className="w-full text-xs"><thead className="tbl-head border-b"><tr>{["Nama","Kontak","Cabang","Status","Poin","Aksi"].map((h) => <th key={h} className="px-6 py-3.5 text-left font-medium">{h}</th>)}</tr></thead><tbody>{filtered.length ? filtered.map((c) => <tr key={c.id} className="tbl-row"><td className="px-6 py-4 font-medium">{c.nama}</td><td className="px-6 py-4 text-jp-muted dark:text-jp-muted-dark">{c.kontak}</td><td className="px-6 py-4 text-jp-muted dark:text-jp-muted-dark">{c.cabang}</td><td className="px-6 py-4"><span className={`badge ${c.status === "Verified" ? "badge-tersedia" : c.status === "Rejected" ? "badge-sold" : "badge-booking"}`}>{c.status}</span></td><td className="px-6 py-4 text-amber-500">⭐ {c.points || 0}</td><td className="px-6 py-4"><div className="flex flex-wrap gap-1.5">{isApprover && c.status === "Pending" && <><button type="button" className="btn-success" onClick={() => void action("approve", c)}>Setujui</button><button type="button" className="btn-error" onClick={() => setRejecting(c)}>Tolak</button></>}{c.status === "Rejected" && <button type="button" className="btn-warning" onClick={() => void action("resubmit", c)}>Ajukan Ulang</button>}</div></td></tr>) : <tr><td colSpan={6}><EmptyState message="Belum ada customer" iconName="usersSvg" /></td></tr>}</tbody></table></div>}
    <Modal isOpen={addOpen} onClose={() => setAddOpen(false)} title="Tambah Customer"><div className="space-y-5"><LabelledInput label="Nama" value={name} onChange={(e) => setName(e.target.value)} /><LabelledInput label="Kontak" value={contact} onChange={(e) => setContact(e.target.value)} /><div className="flex gap-2"><button type="button" className="btn-ghost flex-1" onClick={() => setAddOpen(false)}>Batal</button><button type="button" className="btn-primary flex-1" onClick={() => void create()}>Simpan</button></div></div></Modal>
    <Modal isOpen={Boolean(rejecting)} onClose={() => setRejecting(null)} title="Tolak Customer"><div className="space-y-5"><LabelledTextarea label="Alasan penolakan" rows={4} value={reason} onChange={(e) => setReason(e.target.value)} /><div className="flex gap-2"><button type="button" className="btn-ghost flex-1" onClick={() => setRejecting(null)}>Batal</button><button type="button" className="btn-error flex-1" onClick={() => rejecting && void action("reject", rejecting)}>Tolak</button></div></div></Modal>
  </div>;
}
